version: "3.8"

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT:-15430}:5432

  app:
    build: .
    restart: always
    command: sh ./start_server.sh
    environment:
      APP_ENV: production
    depends_on:
      - db
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT:-8000}:8000

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: >
      --requirepass ${REDIS_PASSWORD}

  worker:
    build: .
    restart: always
    environment:
      REDIS_URL_FOR_CELERY: ${REDIS_URL_FOR_CELERY_PROD}
      FLASK_APP: wsgi:app
      FLASK_ENV: production
      FLASK_DEBUG: 0
      APP_ENV: production
    command: ./start_worker.sh
    depends_on:
      - redis

volumes:
  db_data:
