version: '3'
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}

  app:
    image: simple2b/car-qr-label:0.4.9
    restart: always
    volumes:
      - ./uploads:/home/app/app/static/uploads
    command: sh ./start_server.sh
    environment:
      APP_ENV: production
      TZ: 'America/Toronto'
    env_file:
      - .env
    depends_on:
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.app.rule=Host(`autoqrcode.com`)'
      - 'traefik.http.routers.app.tls=true'
      - 'traefik.http.routers.app.tls.certresolver=myresolver'
      - 'traefik.http.services.app.loadbalancer.server.port=8000'
  backup:
    image: simple2b/pg-backup:1.0

    links:
      - db
    restart: always
    volumes:
      - ./backup:/backup
    environment:
      # scheduler
      SCHEDULE_HOUR: ${SCHEDULE_HOUR:-0}
      SCHEDULE_MINUTE: ${SCHEDULE_MINUTE:-0}
      SCHEDULE_SECOND: ${SCHEDULE_SECOND:-0}
      POSTGRES_HOST: db
      POSTGRES_DATABASE: db
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'
      DAYS_HISTORY: 30
networks:
  default:
    name: qr_network

volumes:
  db_data:
  uploads:
