"""add gift boxes models and sale salereports models

Revision ID: 158767cc1382
Revises: 548e4eb2e262
Create Date: 2024-07-12 14:44:47.102710

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "158767cc1382"
down_revision = "548e4eb2e262"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gift_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("SKU", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=264), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("min_qty", sa.Integer(), nullable=False),
        sa.Column("max_qty", sa.Integer(), nullable=False),
        sa.Column("_is_default", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gift_items")),
        sa.UniqueConstraint("SKU", name=op.f("uq_gift_items_SKU")),
    )
    op.create_table(
        "dealer_gift_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dealer_id", sa.Integer(), nullable=False),
        sa.Column("gift_item_id", sa.Integer(), nullable=False),
        sa.Column("unique_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("description", sa.String(length=264), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealer_id"],
            ["users.id"],
            name=op.f("fk_dealer_gift_items_dealer_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["gift_item_id"],
            ["gift_items.id"],
            name=op.f("fk_dealer_gift_items_gift_item_id_gift_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dealer_gift_items")),
    )
    op.create_table(
        "sale_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_id", sa.String(length=36), nullable=False),
        sa.Column("seller_id", sa.Integer(), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.Column("buyer_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_notfy_by_email", sa.Boolean(), nullable=False),
        sa.Column("is_notfy_by_phone", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["buyer_id"], ["users.id"], name=op.f("fk_sale_reports_buyer_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["label_id"], ["labels.id"], name=op.f("fk_sale_reports_label_id_labels")
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"], ["users.id"], name=op.f("fk_sale_reports_seller_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_reports")),
    )
    op.create_table(
        "gift_boxes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sale_result_id", sa.Integer(), nullable=False),
        sa.Column("dealer_gift_item_id", sa.Integer(), nullable=False),
        sa.Column("unique_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealer_gift_item_id"],
            ["dealer_gift_items.id"],
            name=op.f("fk_gift_boxes_dealer_gift_item_id_dealer_gift_items"),
        ),
        sa.ForeignKeyConstraint(
            ["sale_result_id"],
            ["sale_reports.id"],
            name=op.f("fk_gift_boxes_sale_result_id_sale_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gift_boxes")),
    )
    op.create_table(
        "oil_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("sale_rep_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sale_rep_id"],
            ["sale_reports.id"],
            name=op.f("fk_oil_changes_sale_rep_id_sale_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oil_changes")),
    )

    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.alter_column(
            "url",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.alter_column(
            "url",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )

    op.drop_table("oil_changes")
    op.drop_table("gift_boxes")
    op.drop_table("sale_reports")
    op.drop_table("dealer_gift_items")
    op.drop_table("gift_items")
    # ### end Alembic commands ###
