"""trim_name_not_unique

Revision ID: 178a5fc60bea
Revises: 9c4af1bdebfe
Create Date: 2023-09-04 14:06:26.506465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178a5fc60bea'
down_revision = '9c4af1bdebfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trims', schema=None) as batch_op:
        batch_op.drop_index('ix_trims_name')
        batch_op.create_index(batch_op.f('ix_trims_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trims_name'))
        batch_op.create_index('ix_trims_name', ['name'], unique=False)

    # ### end Alembic commands ###
