"""client index

Revision ID: 23a6d4f25c28
Revises: 233c24676a3c
Create Date: 2023-08-28 12:44:59.727401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a6d4f25c28'
down_revision = '233c24676a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('uq_clients_email', type_='unique')
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.create_unique_constraint('uq_clients_email', ['email'])

    # ### end Alembic commands ###
