"""stripe_customer_id

Revision ID: 249be048ce3d
Revises: 91ef0dba63b6
Create Date: 2023-08-07 12:09:45.204525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249be048ce3d'
down_revision = '91ef0dba63b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_users_stripe_customer_id'), ['stripe_customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_stripe_customer_id'), type_='unique')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
