"""gift

Revision ID: 256cf9b7d150
Revises: 3941b74866dd
Create Date: 2023-08-23 10:15:21.121370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256cf9b7d150'
down_revision = '3941b74866dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gift', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('gift')

    # ### end Alembic commands ###
