"""remove cascade

Revision ID: 2803664c7f49
Revises: 751ce9a0a50b
Create Date: 2023-07-24 09:57:39.463076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2803664c7f49'
down_revision = '751ce9a0a50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_constraint('fk_labels_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_labels_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_logo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_logo_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_logo_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_logo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_logo_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_logo_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_labels_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_labels_user_id_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
