"""url_length

Revision ID: 459b653fbd86
Revises: 5763b5b2e9a7
Create Date: 2023-11-17 22:21:35.171128

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "459b653fbd86"
down_revision = "5763b5b2e9a7"
branch_labels = None
depends_on = None


# with op.get_context().autocommit_block():
#     op.execute("ALTER TYPE usersrole ADD VALUE 'seller'")
#     op.execute("ALTER TYPE usersrole ADD VALUE 'buyer'")
#     op.execute("ALTER TYPE usersrole ADD VALUE 'service'")
#     op.execute("ALTER TYPE usersrole ADD VALUE 'picker'")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
    #     batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    # op.drop_table('apscheduler_jobs')
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.alter_column(
            "url",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("labels", schema=None) as batch_op:
        batch_op.alter_column(
            "url",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
