"""stripe_price_product

Revision ID: 47b507eab6f8
Revises: 249be048ce3d
Create Date: 2023-08-07 12:47:49.410653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b507eab6f8'
down_revision = '249be048ce3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('unit_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stripe_product_prices'))
    )
    op.create_table('stripe_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_product_id', sa.String(length=64), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['stripe_product_prices.id'], name=op.f('fk_stripe_products_price_id_stripe_product_prices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stripe_products'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_products')
    op.drop_table('stripe_product_prices')
    # ### end Alembic commands ###
