"""add image
Revision ID: 4f4a7286a2af
Revises: d53a68255a12
Create Date: 2024-08-30 15:55:54.003836

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.models.utils import DEFUALT_IMAGE_PATH

# revision identifiers, used by Alembic.
revision = "4f4a7286a2af"
down_revision = "d53a68255a12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gift_items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "image_path",
                sa.String(length=512),
                nullable=False,
                server_default=str(DEFUALT_IMAGE_PATH),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gift_items", schema=None) as batch_op:
        batch_op.drop_column("_image")
