"""add new models

Revision ID: 5af7f3b7149b
Revises: 6820846ae95a
Create Date: 2024-07-26 16:13:48.183714

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5af7f3b7149b"
down_revision = "6820846ae95a"
branch_labels = None
depends_on = None


def upgrade():

    # I did not add the downgrade function
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE usersrole ADD VALUE 'seller'")
        op.execute("ALTER TYPE usersrole ADD VALUE 'buyer'")
        op.execute("ALTER TYPE usersrole ADD VALUE 'service'")
        op.execute("ALTER TYPE usersrole ADD VALUE 'picker'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gift_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("SKU", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=264), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("min_qty", sa.Integer(), nullable=False),
        sa.Column("max_qty", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gift_items")),
        sa.UniqueConstraint("SKU", name=op.f("uq_gift_items_SKU")),
    )
    op.create_table(
        "dealer_gift_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dealer_id", sa.Integer(), nullable=False),
        sa.Column("gift_item_id", sa.Integer(), nullable=False),
        sa.Column("unique_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("min_qty", sa.Integer(), nullable=False),
        sa.Column("max_qty", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealer_id"],
            ["users.id"],
            name=op.f("fk_dealer_gift_items_dealer_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["gift_item_id"],
            ["gift_items.id"],
            name=op.f("fk_dealer_gift_items_gift_item_id_gift_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dealer_gift_items")),
    )
    op.create_table(
        "gifts_invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dealer_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("stripe_invoice_id", sa.String(length=64), nullable=False),
        sa.Column("hosted_invoice_url", sa.String(length=512), nullable=False),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealer_id"], ["users.id"], name=op.f("fk_gifts_invoices_dealer_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gifts_invoices")),
    )
    op.create_table(
        "sale_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_id", sa.String(length=36), nullable=False),
        sa.Column("seller_id", sa.Integer(), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.Column("buyer_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("pickup_date", sa.DateTime(), nullable=False),
        sa.Column("is_notfy_by_email", sa.Boolean(), nullable=False),
        sa.Column("is_notfy_by_phone", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=264), nullable=False),
        sa.ForeignKeyConstraint(
            ["buyer_id"], ["users.id"], name=op.f("fk_sale_reports_buyer_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["label_id"], ["labels.id"], name=op.f("fk_sale_reports_label_id_labels")
        ),
        sa.ForeignKeyConstraint(
            ["seller_id"], ["users.id"], name=op.f("fk_sale_reports_seller_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_reports")),
    )
    op.create_table(
        "gift_boxes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sale_result_id", sa.Integer(), nullable=False),
        sa.Column("dealer_gift_item_id", sa.Integer(), nullable=True),
        sa.Column("dealer_id", sa.Integer(), nullable=False),
        sa.Column("unique_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("_sku", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealer_gift_item_id"],
            ["dealer_gift_items.id"],
            name=op.f("fk_gift_boxes_dealer_gift_item_id_dealer_gift_items"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["dealer_id"], ["users.id"], name=op.f("fk_gift_boxes_dealer_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["sale_result_id"],
            ["sale_reports.id"],
            name=op.f("fk_gift_boxes_sale_result_id_sale_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gift_boxes")),
    )
    op.create_table(
        "oil_changes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unique_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("sale_rep_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sale_rep_id"],
            ["sale_reports.id"],
            name=op.f("fk_oil_changes_sale_rep_id_sale_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oil_changes")),
    )
    op.create_table(
        "serivce_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.Column("oil_change_id", sa.Integer(), nullable=True),
        sa.Column("unique_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(length=264), nullable=False),
        sa.Column("file_url", sa.String(length=512), nullable=False),
        sa.ForeignKeyConstraint(
            ["label_id"], ["labels.id"], name=op.f("fk_serivce_records_label_id_labels")
        ),
        sa.ForeignKeyConstraint(
            ["oil_change_id"],
            ["oil_changes.id"],
            name=op.f("fk_serivce_records_oil_change_id_oil_changes"),
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["users.id"],
            name=op.f("fk_serivce_records_service_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_serivce_records")),
    )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("_creator_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_users__creator_id_users"), "users", ["_creator_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_users__creator_id_users"), type_="foreignkey"
        )
        batch_op.drop_column("_creator_id")

    op.drop_table("serivce_records")
    op.drop_table("oil_changes")
    op.drop_table("gift_boxes")
    op.drop_table("sale_reports")
    op.drop_table("gifts_invoices")
    op.drop_table("dealer_gift_items")
    op.drop_table("gift_items")
    # ### end Alembic commands ###
