"""sticker_identifier

Revision ID: 5f513835094e
Revises: 2803664c7f49
Create Date: 2023-07-27 14:24:43.625184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f513835094e'
down_revision = '2803664c7f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sticker_identifier', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('sticker_identifier')

    # ### end Alembic commands ###
