"""add sku

Revision ID: 63268b867b4f
Revises: be3c472fac2e
Create Date: 2024-08-07 16:21:51.749248

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "63268b867b4f"
down_revision = "be3c472fac2e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "dealer_gift_item_replenishments", schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column("sku", sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "dealer_gift_item_replenishments", schema=None
    ) as batch_op:
        batch_op.drop_column("sku")

    # ### end Alembic commands ###
