"""user deleted, label date sold, label views

Revision ID: 751ce9a0a50b
Revises: 18430d8ebfbb
Create Date: 2023-07-24 09:54:11.889625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751ce9a0a50b'
down_revision = '18430d8ebfbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_deactivated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    with op.batch_alter_table('user_logo', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    with op.batch_alter_table('user_logo', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.drop_column('views')
        batch_op.drop_column('date_deactivated')

    # ### end Alembic commands ###
