"""add service records

Revision ID: ae36b5401810
Revises: 0e9ddf4e9208
Create Date: 2024-07-18 15:05:19.942214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae36b5401810'
down_revision = '0e9ddf4e9208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serivce_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('oil_change_id', sa.Integer(), nullable=True),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=264), nullable=False),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name=op.f('fk_serivce_records_label_id_labels')),
    sa.ForeignKeyConstraint(['oil_change_id'], ['oil_changes.id'], name=op.f('fk_serivce_records_oil_change_id_oil_changes')),
    sa.ForeignKeyConstraint(['service_id'], ['users.id'], name=op.f('fk_serivce_records_service_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_serivce_records'))
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    op.drop_table('serivce_records')
    # ### end Alembic commands ###
