"""add DealerGiftIteRreplenishment

Revision ID: b0decd84be89
Revises: 5af7f3b7149b
Create Date: 2024-07-29 14:22:23.759639

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b0decd84be89"
down_revision = "5af7f3b7149b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dealer_gift_item_replenishments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dealer_gift_item_id", sa.Integer(), nullable=False),
        sa.Column("unique_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dealer_gift_item_id"],
            ["dealer_gift_items.id"],
            name=op.f(
                "fk_dealer_gift_item_replenishments_dealer_gift_item_id_dealer_gift_items"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dealer_gift_item_replenishments")),
    )
    with op.batch_alter_table("dealer_gift_items", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_deleted", sa.Boolean(), nullable=False, server_default="0")
        )

    with op.batch_alter_table("gift_boxes", schema=None) as batch_op:
        batch_op.alter_column(
            "dealer_gift_item_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.drop_constraint(
            "fk_gift_boxes_dealer_gift_item_id_dealer_gift_items", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_gift_boxes_dealer_gift_item_id_dealer_gift_items"),
            "dealer_gift_items",
            ["dealer_gift_item_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gift_boxes", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_gift_boxes_dealer_gift_item_id_dealer_gift_items"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_gift_boxes_dealer_gift_item_id_dealer_gift_items",
            "dealer_gift_items",
            ["dealer_gift_item_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.alter_column(
            "dealer_gift_item_id", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("dealer_gift_items", schema=None) as batch_op:
        batch_op.drop_column("is_deleted")

    op.drop_table("dealer_gift_item_replenishments")
    # ### end Alembic commands ###
