"""add description

Revision ID: b1feffbb383c
Revises: 158767cc1382
Create Date: 2024-07-15 13:06:24.459368

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b1feffbb383c"
down_revision = "158767cc1382"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("apscheduler_jobs")
    with op.batch_alter_table("sale_reports", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "description", sa.String(length=264), nullable=False, server_default=""
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sale_reports", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
