"""add shipping_price

Revision ID: be3c472fac2e
Revises: b0decd84be89
Create Date: 2024-07-30 12:15:33.436656

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "be3c472fac2e"
down_revision = "b0decd84be89"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "shipping_price", sa.Float(), nullable=False, server_default="0.0"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("shipping_price")

    # ### end Alembic commands ###
