"""init

Revision ID: defdfeb91033
Revises: 
Create Date: 2023-08-07 16:08:49.537081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defdfeb91033'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('unit_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stripe_product_prices'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'dealer', name='usersrole'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('reset_password_uid', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('name_of_dealership', sa.String(length=64), nullable=False),
    sa.Column('address_of_dealership', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('province', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('postal_code', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.Enum('basic', 'advanced', name='usersplan'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('stripe_customer_id', name=op.f('uq_users_stripe_customer_id'))
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=36), nullable=False),
    sa.Column('sticker_id', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('vehicle_model', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=False),
    sa.Column('trim', sa.String(length=64), nullable=False),
    sa.Column('type_of_vehicle', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('date_received', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_deactivated', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('cart', 'active', 'archived', name='labelstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_labels_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labels'))
    )
    op.create_table('stripe_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_product_id', sa.String(length=64), nullable=False),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['stripe_product_prices.id'], name=op.f('fk_stripe_products_price_id_stripe_product_prices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stripe_products'))
    )
    op.create_table('user_logo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('mimetype', sa.String(length=32), nullable=False),
    sa.Column('file', sa.LargeBinary(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_logo_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_logo'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('current_period_start', sa.Integer(), nullable=False),
    sa.Column('current_period_end', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['stripe_products.id'], name=op.f('fk_subscriptions_product_id_stripe_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('user_logo')
    op.drop_table('stripe_products')
    op.drop_table('labels')
    op.drop_table('users')
    op.drop_table('stripe_product_prices')
    # ### end Alembic commands ###
