"""label_model

Revision ID: fe83949db228
Revises: 37da9d340c9b
Create Date: 2023-07-20 10:19:28.941710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fe83949db228"
down_revision = "37da9d340c9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_logo", schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_logo_user_id_users", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_user_logo_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_logo", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_user_logo_user_id_users"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_user_logo_user_id_users", "users", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###
