name: Build and Deploy

on:
  push:
    tags:
      - 'v*.*.*'

env:
  DOCKER_LOGIN: simple2b
  PROJECT_IMAGE: simple2b/car-qr-label
  STAGE_HOST: ${{ secrets.SSH_HOST_IP }}
  STAGE_USERNAME: ${{ secrets.SSH_USER }}
  STAGE_SSH_KEY: ${{ secrets.SSH_KEY }}
  STAGE_PORT: ${{ secrets.SSH_PORT }}
  SITE_DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  on-develop-branch-check:
    runs-on: ubuntu-latest
    outputs:
      on_develop: ${{ steps.contains_tag.outputs.retval }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: rickstaa/action-contains-tag@v1
        id: contains_tag
        with:
          reference: 'develop'
          tag: '${{ github.ref }}'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Cache poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Setup poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.4

      - name: Install dependencies
        run: |
          poetry install --verbose

      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --show-source --statistics
          poetry run flake8 . --count --exit-zero --max-complexity=10 --statistics

      - name: Run pytest
        run: |
          poetry run pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker meta
        id: project_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.PROJECT_IMAGE }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_LOGIN }}
          password: ${{ env.SITE_DOCKER_ACCESS_TOKEN }}
      - name: Build and Push CarQR image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.project_meta.outputs.tags }}
          labels: ${{ steps.project_meta.outputs.labels }}

  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs:
      - on-develop-branch-check
      - build
    if: ${{ needs.on-develop-branch-check.outputs.on_develop == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Update compose file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.STAGE_HOST }}
          username: ${{ env.STAGE_USERNAME }}
          key: ${{ env.STAGE_SSH_KEY }}
          port: ${{ env.STAGE_PORT }}
          source: docker-compose.dev.yaml
          target: ~/car_qr
      - name: Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ env.STAGE_HOST }}
          username: ${{ env.STAGE_USERNAME }}
          port: ${{ env.STAGE_PORT }}
          key: ${{ env.STAGE_SSH_KEY }}
          script: |
            cd /home/runner/car_qr &&
            mv docker-compose.dev.yaml docker-compose.yaml &&
            docker compose pull &&
            docker compose up -d &&
            docker system prune -f
