jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Upgrade pip and setuptools
        run: |
          python -m pip install --upgrade pip setuptools
      - name: Cache poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - name: Setup poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.4
      - name: Install dependencies
        run: |
          poetry install --verbose
